### ISSUE TITLE
Smartphone view

### ISSUE THREAD

**Issue by Yionel** [nextcloud/weather#34]
Is it possible to hide left bar (with city list) ?
On smartphone (Nexus 5, 5") on Firefox, I can't see main all view with city, temperature, humidity etc. and I can't see at all array hours list predictions.
Thank you 
https://cloud.ionl.fr/index.php/apps/files/?dir=/Photos&fileid=3#

**Comment by berdosi** [comment]
Adding some media queries, may help here - the below CSS moves the city list to the bottom, hides the last columns of the forecast table, and pushes the forecast panels around a bit. I like the way it looks.

```CSS
@media screen and (orientation: portrait) and (max-width: 12cm) and (min-height: 10cm) {
    #app-container {
        display: flex;
        flex-direction: column;
        height: calc(100vh - 50px);
    }
    #city-list-left {
        order: 2;
        width: 100%;
        flex: min-content;
    }
    #city-list-left ul.city-list {
        flex-direction: row;
        display: flex;
        flex-wrap: wrap;
    }
    #city-list-left ul.city-list li {
        flex: min-content;
        min-width: 50%;
    }
    #city-list-left ul.city-list li:last-child {
        flex: auto;
    }
    #city-right {
        display: flex;
        flex-direction: column;
        padding: 0;
    }
    #city-right tr td:nth-of-type(n+4), th:nth-of-type(n+4) {
        display: none;
    }
}
```
![Screen Shot 2019-12-24 at 22 12 32](https://user-images.githubusercontent.com/134611/71425266-b9aa8280-269a-11ea-904a-53a4bf3aeddd.png)
