### ISSUE TITLE
Change units from C to F

### ISSUE THREAD

**Issue by slayt12** [nextcloud/weather#75]
#15 # Steps to reproduce
1. install weather app from nextcloud app store
2. add a city to the list
3. no option to change units

### Expected behaviour
Should be able to change units of weather

### Actual behaviour
all units are defaulted to kelvin and celcius

### Server configuration

**Operating system**:
ubuntu 18.04
**Web server:**
apache2
**Database:**
mariaDB
**PHP version:**
7.0.33-0
**Nextcloud version:** (see Nextcloud admin page)
15.0.8
**Updated from an older Nextcloud/ownCloud or fresh install:**
new install
**Where did you install Nextcloud from:**
univention server
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

**Comment by slayt12** [comment]
I did finally find the settings button, i had to scroll to the bottom below where the weather data was. It would be beneficial to have the button scroll with the bottom of the window, instead of the page.

**Comment by berdosi** [comment]
Setting the below CSS seems to make it more consistent with other Nextcloud apps' behavior; even though their solution is slightly different.
I should test it in Internet Explorer in the coming days.

 ```CSS
#city-list-left {
    display: flex;
    flex-direction: column;
    padding-bottom: 0;
}

#city-right {
    height: calc(100vh - 50px); /* 50px is the header height */
    overflow: auto;
}
```
